services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - frontend-net
    depends_on:
      - image-compare

  image-compare:
      build: ./service-image-compare
      container_name: image-compare
      networks:
        - backend-net
      depends_on:
        - ocr
      environment:
        - REQUEST_OCR_IP="http://ocr:60000"
        - REQUEST_OCR_PORT="60000"
        - IMAGE_COMPARE_IP="0.0.0.0"
        - IMAGE_COMPARE_PORT="60010"
  
  ocr:
    build: ./service-ocr
    container_name: ocr
    networks:
      - frontend-net
      - backend-net
    environment:
      - OCR_IP="0.0.0.0"
      - OCR_PORT="60000"

  test-container:
    image: alpine
    container_name: test-container
    networks:
      - frontend-net
      - backend-net
    command: sh -c "apk update && apk add --no-cache iputils curl man-pages && while true; do sleep 30; done"

networks:
  frontend-net:
    name: frontend-net
    driver: bridge
  card-database-net:
    name: backend-net
    driver: bridge